### ISSUE TITLE
python报错

### ISSUE THREAD

**Issue by jungle-wolf** [CUMLSec/trex#27]
Traceback (most recent call last):
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\count_car.py", line 86, in <module>
    output_image_frame, list_bboxs = objtracker.update(detector, im)
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\objtracker.py", line 55, in update
    _, bboxes = target_detector.detect(image)
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\objdetector.py", line 76, in detect
    pred = self.m(img, augment=False)[0]
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\models\yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\models\yolo.py", line 139, in forward_once
    x = m(x)  # run
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\models\common.py", line 171, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\24579\Desktop\炮哥夺目比检测跟踪代码\deepsort\yolov5-deepsort\models\common.py", line 45, in fuseforward
    return self.act(self.conv(x))
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\24579\.conda\envs\sdsd_torch\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

Process finished with exit code 1

**Comment by yizhicheng1** [comment]
Hi, I would like to ask if you have solved this problem. If you have solved this problem, can you tell me the solution?
